### Register
POST http://127.0.0.1:3000/api/auth/register
Content-Type: application/json

{
  "username": "saleh",
  "password": "saleh"
}

### Login
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
  "username": "hamza",
  "password": "hamza"
}

### Send message
POST http://127.0.0.1:3000/api/box/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjI1MjFkYTExMzQ0Mzc0NTAxMDFjMiIsImJsb2NrZWRCeSI6W10sImlhdCI6MTYwMDM4MDM4OH0.aHuaZMhqF16hE2wfba_mtZrKqG2wLa-03DfnbUMwA4Q

{
  "peerId": "5f6251d1a1134437450101c1",
  "message": "yoo!?"
}

### Get message detail
GET http://127.0.0.1:3000/api/box/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjI1MjFkYTExMzQ0Mzc0NTAxMDFjMiIsImJsb2NrZWRCeSI6W10sImlhdCI6MTYwMDM4MDM4OH0.aHuaZMhqF16hE2wfba_mtZrKqG2wLa-03DfnbUMwA4Q

