### Register
POST https://chaty-11.herokuapp.com/api/auth/register
Content-Type: application/json

{
  "username": "saleh",
  "password": "saleh"
}

### Login
POST https://chaty-11.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "username": "saleh",
  "password": "saleh"
}

### Send message
POST https://chaty-11.herokuapp.com/api/box/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjE1YjE3Y2JlMTlhMDAxZTk4Nzk0NiIsImJsb2NrZWRCeSI6W10sImlhdCI6MTYwMDI5MDk1MH0.LuVOLHfPUSzIDrdX5NHMluCPvYKuoI_zhUzN6DckTMo

{
  "peerId": "5f615ac5cbe19a001e987945",
  "message": "How are you?"
}
