### Register
POST http://127.0.0.1:3000/api/auth/register
Content-Type: application/json

{
  "username": "ahmed",
  "password": "ahmed"
}

### Login
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
  "username": "saleh",
  "password": "saleh"
}

### Send message
POST http://127.0.0.1:3000/api/box/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjEyMTM1YWE3ODk2NWJlMjVlZjg1NiIsImJsb2NrZWRCeSI6W10sImlhdCI6MTYwMDIxNTIwNH0.2scJwkYGxZZkBnFUMRSm56zRnQoJ9oqkE60FMicVfGo

{
  "peerId": "5f6121ce91180382c6a55b25",
  "message": "Good"
}
